name: 'Json Schema Action: Compression'
description: 'Compresses the given json schema into compressed versions'
author: DaanV2
branding:
  icon: box
  color: purple

inputs:
  specificationFile:
    description: The filepath to the specification file
    required: true
runs:
  using: 'composite'
  steps:
    - name: compress
      shell: shell
      working-directory: ${{ github.action_path }}
      run: |
        jscv "${{ inputs.specificationFile }}"
