name: 'Json Schema Action: Compression'
description: 'Compresses the given json schema into compressed versions'
author: DaanV2
branding:
  icon: box
  color: purple

inputs:
  specificationFile:
    description: The filepath to the specification file
    required: true

runs:
  using: 'docker'
  image: 'ghcr.io/daanv2/jsonschemavalidationcompressor.net:v1.0.6'
  args:
    - ${{ inputs.specificationFile }}