# This is a basic workflow to help you get started with Actions

name: Build Compressor

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Action
        uses: actions/checkout@v3
        
      - name: Checkout Compressor
        uses: actions/checkout@v3
        with:
          repository: https://github.com/DaanV2/JsonSchemaValidationCompressor.Net
          path: /home/jsvc-source/
        
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
          
      - name: Compile
        run: |
          dotnet build -c Release -o ${{ github.workdirectory }}
